<?php

namespace App\Domain\Content;

class Content
{
    public $content_id;
    public $title;
    public $slug;
    public $uri;
    public $keywords;
    public $description;
    public $theme;
    public $template;
    public $body;
    public $is_autogenerated;
    public $is_published;
}
