<?php

return [
    'irregularWords' => [
        'children' => 'child',
        'men' => 'man',
        'mice' => 'mouse',
        'teeth' => 'tooth',
        'feet' => 'foot',
        'geese' => 'goose',
        'women' => 'woman',
        'indices' => 'index',
        'matrices' => 'matrix',
        'vertices' => 'vertex',
        'criteria' => 'criterion',
        'alumni' => 'alumnus',
        'analyses' => 'analysis',
        'appendices' => 'appendix',
        'databases' => 'database',
        'theses' => 'thesis',
        'datasets' => 'dataset',
        'personae' => 'persona',
        'people' => 'person',
        // Add more irregular pluralizations and conjugations here
    ],
    'prefixes' => [
        'dis',
        'un',
        'in',
        'im',
        'non',
        'pre',
        'post',
        'sub',
        'super',
        'inter',
        'trans',
        're',
        'anti',
        'de',
        'counter',
        'hyper',
        'infra',
        'extra',
        'micro',
        'macro',
        'multi',
        'auto',
        'cross',
        'hetero',
        'homo',
        'over',
        'under',
        'pseudo',
        'co',
        'mid',
        'mis',
        'out',
        'pro',
        'semi',
        'ultra',
        // Add more prefixes here
    ],
    'suffixes' => [
        'ing',
        'ed',
        'er',
        'est',
        's',
        'es',
        'ly',
        'ment',
        'tion',
        'able',
        'ible',
        'ous',
        'ful',
        'less',
        'ness',
        'ize',
        'ise',
        'y',
        'al',
        'ic',
        'ive',
        'ish',
        'ist',
        'ism',
        'ity',
        'ize',
        'wise',
        'ware',
        'ship',
        'sion',
        'ance',
        'ence',
        // Add more suffixes here
    ],
];
