<?php

return [
    'question' => [
        "How come?",
        "Why's that?",
        "What for?",
        "Explain?",
        "Really?",
        "Any reason?",
        "How so?",
        "Why now?",
        "Source?",
        "Who says?",
        "How many?",
        "Alternatives?",
        "Which one?",
        "When's that?",
        "Prove it?",
        "Why here?",
        "What's up?",
        "How much?",
        "Is it true?",
        "Tell me more?",
        "Any updates?",
        "Project status?",
        "Best practices?",
        "New features?",
        "Performance issues?",
        "Security concerns?",
        "API recommendations?",
        "Latest trends?",
        "Team collaboration?",
        "Upcoming events?",
        "Code examples?",
        "Bug fixes?",
        "New tools?",
        "Learning resources?",
        "Deployment options?",
        "UI/UX improvements?",
        "Automation ideas?",
        "Task prioritization?",
        "Data insights?",
        "Error handling?",
        "What are your goals?",
        "Which features do you need?",
        "How can I assist you?",
        "What is your budget?",
        "What's the timeline?",
        "Do you have any preferences?",
        "Are there any constraints?",
        "Who is your target audience?",
        "Which platform are you targeting?",
        "What are your business objectives?",
        "Can you provide more details?",
        "What is the main purpose of your app?",
        "What's your vision for the project?",
        "Which technologies do you prefer?",
        "What is your experience level?",
        "Do you have any design preferences?",
        "What are your security requirements?",
        "How important is performance?",
        "Do you have a domain name?",
        "What is your hosting plan?",
        "Do you need e-commerce integration?",
        "How do you plan to monetize the app?",
        "What type of content will be on your site?",
        "Do you need a content management system?",
        "What type of user authentication is required?",
        "How many users do you expect?",
        "What is your preferred development methodology?",
        "Do you have any existing assets or resources?",
        "How do you envision the user experience?",
        "What kind of support will you need?",
        "Do you have any examples of similar apps?",
        "What is your marketing strategy?",
        "What's the most important feature?",
        "What are the project milestones?",
        "How do you plan to manage the project?",
        "What is your technical background?",
        "What is your level of expertise in web development?",
        "Do you have a preferred programming language?",
        "What are your expectations for the chat system?",
        "Do you need any third-party integrations?",
        "What are your data storage requirements?",
        "How do you plan to handle updates and maintenance?",
        "What is your preferred method of communication?",
        "What are your reporting requirements?",
        "What are the key performance indicators?",
        "How do you want to track progress?",
        "Do you have a contingency plan?",
        "What are the risks involved?",
        "Do you have any legal or compliance requirements?",
        "What are your data privacy concerns?",
        "What is your plan for user onboarding?",
        "How do you want to handle user feedback?",
        "What are your customer support requirements?",
        "What are your plans for scaling the app?",
        "How do you plan to handle security breaches?",
        "What is your disaster recovery plan?",
        "What are your backup strategies?",
        "Do you have any preferred cloud providers?",
        "What are your plans for future development?",
        "What are the potential challenges?",
        "What are your expectations for the LLM?",
        "How do you plan to address usability?",
        "What are your accessibility requirements?",
        "Do you have any localization needs?",
        "What are your plans for testing?",
        "How do you want to handle bug reports?",
        "What are your expectations for user satisfaction?",
        "What are your plans for user engagement?",
        "Do you have any gamification requirements?",
        "What are your plans for user retention?",
        "What are your plans for user acquisition?",
        "What are your plans for user growth?",
        "Do you have any preferred analytics tools?",
        "How do you plan to track user behavior?",
        "What are your plans for A/B testing?",
        "What are your plans for optimization?",
        "How do you plan to handle content updates?",
        "What are your plans for version control?",
        "What are your plans for collaboration?",
        "What are your plans for code review?",
        "How do you plan to ensure code quality?",
        "What are your plans for documentation?",
        "Do you have any preferred project management tools?",
        "What are your plans for user training?",
        "How do you plan to measure success?",
        "What are your plans for post-launch support?",
        "What are the next steps?",
        "How can we improve our workflow?",
        "Is there a more efficient solution?",
        "What resources do we need?",
        "Are we on the right track?",
        "How do you envision the final product?",
        "What obstacles are we facing?",
        "Can you provide more details?",
        "What are the key milestones?",
        "How can we better meet user needs?",
        "What's the status of the project?",
        "How can we ensure data privacy?",
        "What are the risks involved?",
        "What's our long-term vision?",
        "How can we optimize our processes?",
    ],
    'statement'=> [
        "Yes.",
        "No.",
        "Sure",
        "Yep",
        "Uh-huh",
        "Definitely",
        "Affirmative",
        "Indeed",
        "Agreed",
        "Okay",
        "Yup",
        "Fine",
        "Approved",
        "Roger",
        "Aye",
        "Yea",
        "Alright",
        "Accept",
        "Granted",
        "Positively",
        "Undoubtedly",
        "True",
        "Nope",
        "Nah",
        "Negative",
        "No way",
        "Not at all",
        "Certainly not",
        "Untrue",
        "Refuse",
        "Veto",
        "Nay",
        "Decline",
        "Not really",
        "Doubtful",
        "Reject",
        "No thanks",
        "Not likely",
        "Not happening",
        "Impossible",
        "Disallow",
        "Not ever",
        "Disapprove",
        "Unlikely",
        "Never",
        "Maybe.",
        "Nevermind.",
        "Agreed.",
        "Disagree.",
        "Confirmed.",
        "Denied.",
        "Unsure.",
        "Exactly.",
        "Incorrect.",
        "Right.",
        "Wrong.",
        "Got it.",
        "Proceed.",
        "Wait.",
        "Noted.",
        "Forget it.",
        "Complicated.",
        "Simple.",
        "Absolutely.",
        "Certainly.",
        "Of course.",
        "Task completed.",
        "Bug resolved.",
        "Performance improved.",
        "Security strengthened.",
        "API integrated.",
        "New feature added.",
        "Documentation updated.",
        "Code refactored.",
        "UI redesigned.",
        "UX enhanced.",
        "Meeting scheduled.",
        "Deadline extended.",
        "Resources allocated.",
        "Team expanded.",
        "Project delayed.",
        "Data analyzed.",
        "Test passed.",
        "Test failed.",
        "Server upgraded.",
        "Not implemented.",
        "I prefer using an SQL database.",
        "I'm interested in a mobile app.",
        "Our main goal is to increase user engagement.",
        "We need to optimize the website for SEO.",
        "I'm looking for a user-friendly interface.",
        "The application should be scalable.",
        "We need strong security measures in place.",
        "Our budget is limited for this project.",
        "I'd like to use a cloud-based infrastructure.",
        "We want a custom design for our website.",
        "I think React is a great choice for our front-end.",
        "The project deadline is in two months.",
        "We need to prioritize user privacy.",
        "Our team is experienced with PHP.",
        "I'd like to include machine learning capabilities.",
        "The app should have a responsive design.",
        "I think we should use an Agile development approach.",
        "We need to improve website loading times.",
        "Our target audience is primarily mobile users.",
        "We're interested in integrating third-party APIs.",
        "We need a user management system.",
        "I'd like to use a NoSQL database for flexibility.",
        "We want to prioritize accessibility.",
        "The application should be easy to maintain.",
        "We want to use a microservices architecture.",
        "I'm looking for a reliable hosting provider.",
        "We need to focus on marketing strategies.",
        "Our goal is to improve customer satisfaction.",
        "We're aiming for a fast time to market.",
        "I'd like to explore different pricing models.",
        "I'm interested in implementing a content management system.",
        "We need an efficient search functionality.",
        "I'd like to include social media integration.",
        "We want to include analytics and reporting features.",
        "I think we should consider progressive web app development.",
        "I'm concerned about data storage and backups.",
        "We should focus on performance optimization.",
        "Our team has experience with Python.",
        "We need a way to manage user permissions.",
        "I'd like to use a containerization technology like Docker.",
        "We need a solid test strategy.",
        "I'd like to explore different deployment options.",
        "We want a custom e-commerce solution.",
        "Our goal is to improve user retention.",
        "We need to focus on cross-platform compatibility.",
        "We want to include a chatbot for customer support.",
        "I'm looking for a robust error handling system.",
        "We need a plan for database migrations.",
        "I'd like to use a CI/CD pipeline.",
        "We're looking to create a data-driven application.",
        "I appreciate your input.",
        "The issue has been resolved.",
        "We're making progress.",
        "The feature has been removed.",
        "I'll look into that.",
        "Keep up the good work.",
        "The deadline is approaching.",
        "We've met our goals.",
        "Your feedback is valuable.",
        "We've encountered a setback.",
        "Let's regroup and reassess.",
        "The new release is live.",
        "I've found a potential solution.",
        "We need to prioritize tasks.",
        "The demo was successful.",
        "I'm happy with the results.",
        "We should consider a new approach.",
        "Let's stick to the plan.",
        "The project is on track.",
        "I'm confident in our team.",
        "We've hit a roadblock.",
        "We need to make a decision.",
        "The design needs improvement.",
        "Let's brainstorm new ideas.",
        "I'll update the documentation.",
        "We need a different strategy.",
        "The prototype is ready.",
        "We should do more testing.",
        "Our collaboration is effective.",
        "I'm satisfied with the outcome.",
        "The requirements have changed.",
        "We need more time.",
        "The project is complete.",
        "I've learned a lot from this experience.",
        "We should focus on user feedback.",
        "Our efforts are paying off.",
        "I've submitted the report.",
        "We need to address these issues.",
        "Let's reevaluate our priorities.",
        "I'm excited about the future.",
        "The team is highly skilled.",
        "We've made a breakthrough.",
        "The data is insightful.",
        "We should celebrate our success.",
        "I'm eager to tackle new challenges.",
        "The project has been a valuable learning experience.",
        "I'm impressed with our progress.",
        "We've reached a consensus.",
        "The results are promising.",
        "Our teamwork has been exceptional.",
    ],
    'stop' => [
        "Stop",
        "Hold on",
        "Wait a moment",
        "Pause",
        "Hold up",
        "Cease",
        "Halt",
        "Hold",
        "Hang on",
        "Give me a moment",
        "Hold your horses",
        "Wait",
        "Take a break",
        "Wait a second",
        "Slow down",
        "Hold it right there",
        "Hold off",
        "Stand by",
        "Hold the line",
        "Freeze",
        "Stop for a moment",
        "Put a hold on that",
        "Let's take a break",
        "Hold on a minute",
        "Just a moment",
        "Let's pause here",
        "Can we stop for a second?",
        "Give me a second",
        "Wait up",
        "Hold everything",
        "Let's hold off on that",
        "Hold that thought",
        "Hold on a sec",
        "Hold your thoughts",
        "Wait a minute",
        "Put it on pause",
        "Hold the phone",
        "Hold on to that thought",
        "Take a pause",
        "Wait for a moment",
        "Hang on a second",
        "Wait a bit",
        "Let's stop here",
        "Hold the process",
        "Let's wait a moment",
        "Give me a moment to think",
        "Hold it",
        "Hold on tight",
        "Let's put that on hold",
        "Hold your fire",
        "Hold on for a moment.",
        "Wait a second.",
        "Let's take a break.",
        "Put it on pause.",
        "Can we stop here?",
        "Just a moment, please.",
        "Hold that thought.",
        "Let's halt for now.",
        "Give me a second.",
        "Wait, let me think.",
        "Hold off for a bit.",
        "Let's postpone this.",
        "Pause, please.",
        "We should stop and reconsider.",
        "Let's take a step back.",
        "Hold everything.",
        "Could we take a breather?",
        "Can we hold off on that?",
        "Let's stop and regroup.",
        "I need a moment.",
        "Just a minute, please.",
        "Let's take a timeout.",
        "Wait a moment.",
        "Can we reschedule this?",
        "I'd like to pause here.",
        "Let's freeze for a moment.",
        "Hold your horses.",
        "We should stop and think.",
        "Let's delay this for now.",
        "Can we take a short break?",
        "Hold up for a second.",
        "Let's suspend this for now.",
        "Wait, let's reconsider.",
        "I need to pause for a moment.",
        "Let's come back to this later.",
        "Can we pause the discussion?",
        "Hold on, I need to think.",
        "Let's adjourn for now.",
        "I'd like to stop and reflect.",
        "Wait, I have a question.",
        "Can we defer this for now?",
        "Let's take a rain check.",
        "Hold on, I need more information.",
        "Let's take a pause here.",
        "Wait, I need to double-check something.",
        "Let's halt the discussion.",
        "Hold on, I'm not sure.",
        "I'd like to cancel for now.",
        "Can we take a short pause?",
        "Wait, I have a concern.",
    ]
];