<?php
namespace App\Business\Http\Api\Admin;

use BlueFission\Services\Service;
use BlueFission\Services\Request;
use BlueFission\Connections\Database\MySQLLink;
use App\Domain\Content\Queries\IAllContentQuery;
use App\Domain\Content\Repositories\IContentRepository;
use App\Domain\Content\Content;

class ContentController extends Service {

    public function index( IAllContentQuery $query ) {
        $pages = $query->fetch();
        return response($pages);
    }

    public function find( $page_id, IContentRepository $repository ) {
        $page = $repository->find($page_id);
        return response($page);
    }

    public function save( Request $request, IContentRepository $repository )
    {
        // Create new page model
        $page = new Content;
        $page->page_id = $request->page_id;
        $page->title = $request->title;
        $page->slug = $request->slug;
        $page->uri = $request->uri;
        $page->keywords = $request->keywords;
        $page->description = $request->description;
        $page->is_published = $request->is_published;
        $page->is_autogenerated = $request->is_autogenerated;
        $page->content = $request->content;
        $page->template = $request->template;

        // Save the new page
        $response = $repository->save($page);

        // Return the id
        return response($response);
    }
}